[package]
name = "cargo-backup"
version = "0.1.0"
edition = "2021"
authors = ["Kiramily"]
keywords = ["cli"]
description = "Backup utilty for cargo"
license = "MIT"
repository = "https://github.com/Kiramily/cargo-backup"
homepage = "https://github.com/Kiramily/cargo-backup"
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
